version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:4.20.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-network

  chrome:
    image: selenium/node-chrome:4.20.0
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    networks:
      - selenium-network

  edge:
    image: selenium/node-edge:4.20.0
    container_name: edge
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
    networks:
      - selenium-network

networks:
  selenium-network:
    driver: bridge