Browser : Chrome
ChromeDriverClassName : webdriver.chrome.driver
ChromeDriverClassPath : D:\\Prathamesh\\Selenium\\Supported_JarFiles\\chromedriver-win64\\chromedriver.exe

EdgeDriverClassName : webdriver.edge.driver
EdgeDriverClassPath : D:\\Prathamesh\\Selenium\\Supported_JarFiles\\msedgedriver.exe

Grid : NoGrid
GridURL : http://localhost:4444/wd/hub

AppURL : https://demoqa.com/login
UserName : TestUser
Password : xlbbYx/FE5e1C54YwhbwoA==

DBurl : jdbc:mysql://localhost:3306/demoQA
DBUserName : root
DBPassword : GXNgb6g6uG8fhaemAp5ydg==